forward:
  requestHeaderUserId: "fw-gateway-user-id"
users:
  serverPort: ${server.ms.host}:${port.users}
  tokenCookieParamName: "token"
  uriTokenVerificationPath: "/users/token"
spring:
  cloud:
    gateway:
      routes:
        # Microservices
        # Movies
        - id: movies_public_get
          uri: ${server.ms.host}:${port.movies}
          predicates:
            - Path=/movies/**
            - Method=GET
        # Shows
        - id: shows_public
          uri: ${server.ms.host}:${port.shows}
          predicates:
            - Path=/shows/**
            - Method=GET
        # Users
        - id: users_public
          uri: ${server.ms.host}:${port.users}
          predicates:
            - Path=/users/**
            - Method=POST
        - id: users_private
          uri: ${server.ms.host}:${port.users}
          predicates:
            - Path=/users/private/**
          filters:
            - TokenVerificationFilter