# This configuration is only for development, not for production!
services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-chapter-ms-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - messaging

networks:
  messaging:
    driver: bridge